// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

/// @title IZkVerifier
/// @notice The interface every on-chain UltraPlonk/Honk verifier generated by
/// Barretenberg's `bb write_solidity_verifier` implements.
/// @dev This exact signature — `verify(bytes calldata proof, bytes32[] calldata
/// publicInputs) external view returns (bool)` — is what `bb`'s codegen emits for a
/// Noir circuit compiled with `nargo compile` (see integrity-zkp/README.md for the full
/// `nargo compile` -> `bb write_vk` -> `bb write_solidity_verifier` pipeline, §5 of the
/// interface contract). `view` rather than `pure` because the real generated verifier
/// reads no storage but is not literally side-effect-free at the EVM level (it uses
/// precompiled contracts for the pairing check); `bytes32[]` for public inputs matches
/// Noir's field-element public input encoding (each Noir `Field` public input becomes
/// one bytes32 word, big-endian, reduced mod the BN254 scalar field).
///
/// Every contract in this package that needs to check a ZK proof (ReputationRegistry)
/// depends on this interface, never on the concrete UltraPlonkVerifier implementation —
/// that's what lets `make generate-verifier` swap the placeholder for the real generated
/// contract without touching a single calling contract.
interface IZkVerifier {
    function verify(bytes calldata proof, bytes32[] calldata publicInputs) external view returns (bool);
}
