// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {Test} from "forge-std/Test.sol";
import {Clones} from "@openzeppelin/contracts/proxy/Clones.sol";
import {ReputationRegistry} from "../src/oracle/ReputationRegistry.sol";
import {StateAnchor} from "../src/oracle/StateAnchor.sol";
import {IZkVerifier} from "../src/oracle/IZkVerifier.sol";
import {UltraPlonkVerifier} from "../src/oracle/UltraPlonkVerifier.sol";

/// @notice Exercises the real division of labour described in ReputationRegistry's
/// NatSpec: the oracle pushes a pre-boost `baseScore`, and the ZK_boost multiplier is
/// only ever applied after this contract independently verifies a proof against a
/// leaf anchored in a real StateAnchor Merkle tree. The IZkVerifier itself is mocked
/// via `vm.mockCall` (per the task's own instruction) since the real Barretenberg
/// verifier is generated by the sibling integrity-zkp package and isn't available here
/// — but the Merkle anchoring and score bookkeeping around it are fully real.
contract ReputationRegistryTest is Test {
    ReputationRegistry registry;
    StateAnchor anchor;
    address admin = makeAddr("admin");
    address mockVerifier = address(0xBEEF);
    address agent = makeAddr("agent");

    bytes32 leaf;
    bytes32 sibling;
    bytes32 root;
    bytes32[] proof;

    function _hashPair(bytes32 a, bytes32 b) internal pure returns (bytes32) {
        return a < b ? keccak256(abi.encodePacked(a, b)) : keccak256(abi.encodePacked(b, a));
    }

    function setUp() public {
        anchor = new StateAnchor(admin);
        // ReputationRegistry is a clone-only contract (its own constructor calls
        // _disableInitializers so the implementation itself can never be initialized —
        // see the contract's NatSpec). Deploy an implementation, then a real EIP-1167
        // clone of it, exactly as AgentPrimitivesFactory does in production.
        ReputationRegistry impl = new ReputationRegistry();
        registry = ReputationRegistry(Clones.clone(address(impl)));
        // `admin` stands in for both the agent's SovereignAgent (DEFAULT_ADMIN_ROLE) and
        // the protocol oracle signer (ORACLE_ROLE) here, since this unit test only cares
        // about ReputationRegistry's own logic — the real distinction between the two is
        // exercised in AgentPrimitivesFactory.t.sol.
        registry.initialize(admin, admin, mockVerifier, address(anchor));

        leaf = keccak256(abi.encodePacked("agent-report:", agent));
        sibling = keccak256(abi.encodePacked("sibling-leaf"));
        root = _hashPair(leaf, sibling);

        proof = new bytes32[](1);
        proof[0] = sibling;

        vm.prank(admin);
        anchor.anchorRoot(root);
    }

    function test_oracleUpdatesBaseScore() public {
        vm.prank(admin); // admin holds ORACLE_ROLE from constructor
        registry.updateScore(agent, 750);

        (uint256 base, uint256 effective, bool boosted,) = registry.getAgent(agent);
        assertEq(base, 750);
        assertEq(effective, 750);
        assertFalse(boosted);
    }

    function test_nonOracleCannotUpdateScore() public {
        vm.expectRevert();
        registry.updateScore(agent, 750);
    }

    function test_submitZkAttestation_appliesBoost() public {
        vm.prank(admin);
        registry.updateScore(agent, 1000);

        vm.mockCall(
            mockVerifier, abi.encodeWithSelector(IZkVerifier.verify.selector), abi.encode(true)
        );

        vm.prank(agent);
        registry.submitZkAttestation(agent, hex"1234", new bytes32[](0), root, leaf, proof);

        (uint256 base, uint256 effective, bool boosted,) = registry.getAgent(agent);
        assertEq(base, 1000);
        assertEq(effective, 1150); // 1000 * 1.15
        assertTrue(boosted);
    }

    function test_boostExpiresAfterReportingPeriod() public {
        vm.prank(admin);
        registry.updateScore(agent, 1000);

        vm.mockCall(mockVerifier, abi.encodeWithSelector(IZkVerifier.verify.selector), abi.encode(true));
        vm.prank(agent);
        registry.submitZkAttestation(agent, hex"1234", new bytes32[](0), root, leaf, proof);

        assertEq(registry.effectiveScore(agent), 1150);

        vm.warp(block.timestamp + registry.reportingPeriod() + 1);
        assertEq(registry.effectiveScore(agent), 1000);
        assertFalse(registry.isZkBoosted(agent));
    }

    function test_onlyAgentCanSubmitOwnProof() public {
        vm.mockCall(mockVerifier, abi.encodeWithSelector(IZkVerifier.verify.selector), abi.encode(true));

        address impersonator = makeAddr("impersonator");
        vm.prank(impersonator);
        vm.expectRevert(ReputationRegistry.OnlyAgentCanSubmitOwnProof.selector);
        registry.submitZkAttestation(agent, hex"1234", new bytes32[](0), root, leaf, proof);
    }

    function test_attestationFailsIfLeafNotAnchored() public {
        vm.mockCall(mockVerifier, abi.encodeWithSelector(IZkVerifier.verify.selector), abi.encode(true));

        bytes32 unanchoredLeaf = keccak256("never-anchored");
        vm.prank(agent);
        vm.expectRevert(ReputationRegistry.LeafNotAnchored.selector);
        registry.submitZkAttestation(agent, hex"1234", new bytes32[](0), root, unanchoredLeaf, proof);
    }

    function test_attestationFailsIfVerifierRejects() public {
        vm.mockCall(mockVerifier, abi.encodeWithSelector(IZkVerifier.verify.selector), abi.encode(false));

        vm.prank(agent);
        vm.expectRevert(ReputationRegistry.InvalidProof.selector);
        registry.submitZkAttestation(agent, hex"1234", new bytes32[](0), root, leaf, proof);
    }

    /// @notice Against the REAL placeholder verifier (not a test mock): confirms the
    /// placeholder fails closed by reverting, so the ZK-boost path is provably
    /// unusable until `make generate-verifier` swaps in the real contract.
    function test_placeholderVerifierRevertsInsteadOfMocking() public {
        UltraPlonkVerifier placeholder = new UltraPlonkVerifier();
        vm.prank(admin);
        registry.setZkConfig(address(placeholder), address(anchor));

        vm.prank(agent);
        vm.expectRevert(UltraPlonkVerifier.PlaceholderVerifierNotYetGenerated.selector);
        registry.submitZkAttestation(agent, hex"1234", new bytes32[](0), root, leaf, proof);
    }

    function test_bridgeRoleCanUpdateScore() public {
        address bridge = makeAddr("bridge");
        bytes32 bridgeRole = registry.BRIDGE_ROLE();
        vm.prank(admin);
        registry.grantRole(bridgeRole, bridge);

        vm.prank(bridge);
        registry.updateScoreByBridge(agent, 555);

        (uint256 base,,,) = registry.getAgent(agent);
        assertEq(base, 555);
    }
}
