//! Signature verification for incoming agent-signed data, and the canonical JSON
//! encoding that signatures are computed over.
//!
//! Two schemes are supported (§4.1/§4.2 of the interface contract): Ed25519 for
//! DID-identified agents, and EIP-191 for agents whose identity is an Ethereum
//! address (e.g. one backed by `contracts/`'s `SovereignAgent`). Which one
//! applies is determined by what the *registered* agent record actually has on
//! file — never by trusting a claim in the request itself, since that would let
//! an attacker pick whichever verification scheme they can forge.

pub mod eip191;
pub mod ed25519;

use serde::Serialize;
use serde_json::Value;
use std::collections::BTreeMap;
use std::io;

/// Recursively re-serializes a JSON value with object keys sorted lexicographically,
/// producing a deterministic byte representation for signing/verification.
///
/// This matters because `serde_json::Value`'s default `Map` preserves insertion
/// order (or hashes, depending on feature flags) — neither is guaranteed stable
/// across languages/serializers. Every producer (integrity-sdk in Python,
/// integrity-cli, this oracle) MUST agree on exactly this encoding, or signatures
/// generated by one will fail to verify against another. Sorting keys is the
/// simplest scheme that's easy to reproduce in Python (`json.dumps(..., sort_keys=True,
/// separators=(',', ':'))`) and Rust alike.
pub fn canonicalize_json(value: &Value) -> Value {
    match value {
        Value::Object(map) => {
            let sorted: BTreeMap<String, Value> = map
                .iter()
                .map(|(k, v)| (k.clone(), canonicalize_json(v)))
                .collect();
            serde_json::to_value(sorted).expect("re-serializing a sorted map cannot fail")
        }
        Value::Array(items) => Value::Array(items.iter().map(canonicalize_json).collect()),
        other => other.clone(),
    }
}

/// `serde_json`'s `CompactFormatter` (what plain `serde_json::to_vec` uses) emits
/// non-ASCII string content as raw UTF-8 bytes. Every producer this oracle must
/// verify against (`integrity-sdk/integrity_sdk/bcc.py`, `bcc_middleware/app/
/// canonical.py`) instead pins Python's `ensure_ascii=True` — non-ASCII characters
/// escaped as `\uXXXX` (surrogate pairs for astral code points) — and both modules'
/// own docstrings warn in so many words that "a Rust... implementation using a
/// different default here would produce a different byte string and a different
/// hash/signature". This formatter closes that gap: it overrides only
/// `write_string_fragment` (the rest of the `Formatter` trait's default methods,
/// which `CompactFormatter` also just uses unmodified, are inherited unchanged), so
/// ASCII content is written byte-for-byte identically to before and only non-ASCII
/// characters take the escaped path.
///
/// Confirmed real, not hypothetical: this was previously masked because nothing
/// successfully reached signature verification at all (see `handlers.rs`'s
/// `ingest_telemetry` — the SDK's request used to fail JSON deserialization before
/// ever reaching a signature check, a separate bug fixed 2026-07-11 in
/// `integrity-sdk/integrity_sdk/client.py`). Once that fix landed, any telemetry
/// content containing non-ASCII text (accented characters, CJK, emoji — nothing
/// exotic) would have silently failed signature verification against this
/// oracle's ASCII-only canonicalization, with no indication why.
struct AsciiEscapingFormatter;

impl serde_json::ser::Formatter for AsciiEscapingFormatter {
    fn write_string_fragment<W: ?Sized>(&mut self, writer: &mut W, fragment: &str) -> io::Result<()>
    where
        W: io::Write,
    {
        // Fragments received here never contain a quote, backslash, or control
        // character — serde_json's string formatter already splits those out to
        // `write_char_escape` before/after calling this, exactly the same
        // separation Python's json encoder makes internally. So this only ever
        // needs to decide ASCII-passthrough vs. non-ASCII-escape, matching
        // `ensure_ascii=True`'s actual scope, not backslash/quote handling too.
        let mut buf = [0u16; 2];
        for c in fragment.chars() {
            if c.is_ascii() {
                writer.write_all(&[c as u8])?;
            } else {
                for unit in c.encode_utf16(&mut buf) {
                    write!(writer, "\\u{:04x}", unit)?;
                }
            }
        }
        Ok(())
    }
}

/// Canonical JSON bytes for signing: sorted keys, no extraneous whitespace, and
/// (see `AsciiEscapingFormatter`) non-ASCII content escaped exactly like Python's
/// `json.dumps(..., ensure_ascii=True)` — the convention every producer this oracle
/// verifies against actually uses. Callers sign/verify over these exact bytes.
pub fn canonical_json_bytes(value: &Value) -> Vec<u8> {
    let canonical = canonicalize_json(value);
    let mut buf = Vec::new();
    let mut ser = serde_json::Serializer::with_formatter(&mut buf, AsciiEscapingFormatter);
    canonical
        .serialize(&mut ser)
        .expect("canonical JSON serialization cannot fail");
    buf
}

/// What an agent is currently registered to authenticate with. An agent may have
/// either, both, or (if this is ever constructed incorrectly) neither — callers
/// must handle the "neither" case explicitly rather than assuming one is always
/// present.
pub struct AgentVerificationMethods<'a> {
    pub ed25519_pubkey_hex: Option<&'a str>,
    pub eth_address_hex: Option<&'a str>,
}

#[derive(Debug, thiserror::Error)]
pub enum VerifyError {
    #[error("agent has no registered verification method")]
    NoVerificationMethod,
    #[error("ed25519 verification error: {0}")]
    Ed25519(#[from] ed25519::Ed25519Error),
    #[error("eip191 verification error: {0}")]
    Eip191(#[from] eip191::Eip191Error),
}

/// Verifies `signature_hex` over `message` against whichever verification
/// method(s) the agent is actually registered with. Tries Ed25519 first (the
/// protocol's primary DID-based scheme), then EIP-191, and only succeeds if at
/// least one registered method validates — this is a deliberate OR, not a
/// fallback-on-failure: an agent registered with both a DID key and an eth
/// address can sign with either.
///
/// Replaces the old prototype's `verify_agent_signature`, whose entire bypass —
/// skip verification if `agent_id.starts_with("agent_")` — has no analog here:
/// there is no code path that returns "verified" without checking a real signature.
pub fn verify_agent_signature(
    message: &[u8],
    signature_hex: &str,
    methods: &AgentVerificationMethods,
) -> Result<bool, VerifyError> {
    if methods.ed25519_pubkey_hex.is_none() && methods.eth_address_hex.is_none() {
        return Err(VerifyError::NoVerificationMethod);
    }

    if let Some(pubkey) = methods.ed25519_pubkey_hex {
        if ed25519::verify_ed25519_signature(message, signature_hex, pubkey)? {
            return Ok(true);
        }
    }
    if let Some(address) = methods.eth_address_hex {
        if eip191::verify_eip191_signature(message, signature_hex, address)? {
            return Ok(true);
        }
    }
    Ok(false)
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn canonicalize_sorts_nested_object_keys() {
        let value = json!({"b": 1, "a": {"z": 1, "y": 2}, "c": [3, 2, 1]});
        let canonical = canonical_json_bytes(&value);
        let expected = br#"{"a":{"y":2,"z":1},"b":1,"c":[3,2,1]}"#;
        assert_eq!(canonical, expected);
    }

    #[test]
    fn canonicalize_is_deterministic_regardless_of_input_key_order() {
        let a = json!({"z": 1, "a": 2});
        let b = json!({"a": 2, "z": 1});
        assert_eq!(canonical_json_bytes(&a), canonical_json_bytes(&b));
    }

    #[test]
    fn canonicalize_escapes_non_ascii_matching_python_ensure_ascii_true() {
        // Expected bytes are exactly what `json.dumps({"name": "café 日本語"},
        // sort_keys=True, separators=(",", ":"), ensure_ascii=True)` produces in
        // Python -- the convention integrity-sdk/bcc.py and bcc_middleware/
        // canonical.py both pin. Lowercase hex, no surrogate pairs needed here
        // since every character is in the Basic Multilingual Plane. Written as a
        // non-raw byte string (not `br#"..."#`) so `\\u00e9` etc. are the six
        // literal ASCII bytes `\`, `u`, `0`, `0`, `e`, `9` -- the escaped form
        // this fix produces -- not the actual café/日本語 characters.
        let value = json!({"name": "café 日本語"});
        let canonical = canonical_json_bytes(&value);
        let expected: &[u8] = b"{\"name\":\"caf\\u00e9 \\u65e5\\u672c\\u8a9e\"}";
        assert_eq!(canonical, expected);
    }

    #[test]
    fn canonicalize_escapes_astral_characters_as_surrogate_pairs() {
        // U+1F389 (party popper emoji) is outside the BMP -- Python's json
        // module (and every other ensure_ascii=True implementation) encodes it
        // as a UTF-16 surrogate pair: 🎉. Confirms `encode_utf16`'s
        // pairing is wired correctly, not just single-BMP-codepoint escaping.
        let value = json!({"emoji": "\u{1f389}"});
        let canonical = canonical_json_bytes(&value);
        let expected: &[u8] = b"{\"emoji\":\"\\ud83c\\udf89\"}";
        assert_eq!(canonical, expected);
    }

    #[test]
    fn canonicalize_still_handles_quotes_and_backslashes_correctly() {
        // Confirms AsciiEscapingFormatter's override doesn't interfere with
        // serde_json's own quote/backslash/control-char escaping, which happens
        // via write_char_escape before write_string_fragment ever sees them.
        let value = json!({"text": "say \"hi\"\\bye"});
        let canonical = canonical_json_bytes(&value);
        let expected = br#"{"text":"say \"hi\"\\bye"}"#;
        assert_eq!(canonical, expected);
    }

    #[test]
    fn no_verification_method_is_a_distinct_error_not_a_default_allow() {
        let methods = AgentVerificationMethods {
            ed25519_pubkey_hex: None,
            eth_address_hex: None,
        };
        let result = verify_agent_signature(b"anything", "0xdead", &methods);
        assert!(matches!(result, Err(VerifyError::NoVerificationMethod)));
    }
}
